### ISSUE TITLE
429 Response code is 429. Body: message => rate limited; 

### ISSUE THREAD

**Issue by smmgeeks** [datvance/noinstagram#1]
hello , I've got dat  - "429 Response code is 429. Body: message => rate limited; status => fail; Something went wrong. Please report issue."

how can I fix it?
Thanks!

**Comment by smmgeeks** [comment]
UDP:
fix
in Request.php - I've commented
423
425

Error cause of CURLOPT_SSL_VERIFYPEER

**Comment by datvance** [comment]
Ok, thanks for the report. I'm not sure that actually fixed your problem, but glad it's working for you.
