### ISSUE TITLE
Video Posts are Broken

### ISSUE THREAD

**Issue by Suleman-Elahi** [datvance/noinstagram#3]
The Video posts don't show up in the feed.

![image](https://user-images.githubusercontent.com/24384996/66696287-407ccf80-ece8-11e9-87e1-993025a58c4d.png)

**Comment by datvance** [comment]
I think this may have been an issue upstream with the scraper, which they've fixed
https://github.com/postaddictme/instagram-php-scraper/releases/tag/v0.8.35
